version: "3.9"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "1000m"
    max-file: "1"

services:
  nginx:
    image: "nginx:alpine"
    ports: 
      - "195.140.147.32:80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www:/var/www
    depends_on:
      - php
    networks:
      - network
    logging: *logging

  php:
    build: .
    ports:
      - ":9000:9000"
    volumes:
      - ./www:/var/www
    networks:
      - network

    healthcheck:
      test: curl --silent http://nginx | grep -c works > /dev/null
      interval: 5s
      timeout: 5s
    
    logging: *logging

networks:
  network:
